Alvin's question
openinnovation-hotel-check-in-out/ideation pull request #10
Opened 2020-08-04 09:05 UTC by alvinlim540

Some update to the question raised by @Zhiyuan-Amos 

- inherit code base or build from scratch?
- deployment for front end/back-end
- Tech stack: framework preferred?

Digital Concierge Questions
A run-thru of the digital concierge process

links of existing solution
CI/CO
Digital Concierge

2020-08-04 09:14 UTC, Zhiyuan-Amos commented
@ahyong92 can you help Alvin with the merge conflict & it seems to be a problem of reusing the same branch

2020-08-05 08:28 UTC, Zhiyuan-Amos requested changes
Made a brief review. In summary, there are multiple English mistakes in the document. Ideally, we don't want to spend time reviewing each other's English, so put your content through a English checker first before submitting a PR.

Also, there are multiple stylistic issues e.g. unnecessary new lines, missing new line. To ensure that the content is easy to read and modify, we should keep the style the same, as if this document is done by a single person.

The above also applies for how the content is being written. For example:

> f. Techstack related:
    1. Any preferred frameworks?

Our questions are written in complete sentences, so this question is out of place. It should have been better phrased as something like:

> Are there any restrictions on the tech stack used for implementing the solution?

Lastly, I tend to type in a more casually and less refined over text, which should not be directly copied here. For e.g.

> Front-end: Are we supposed to host the app on app store? Or do we need an app, or just web will do?

I type in such a manner so that I don't spend that much time to phrase everything nicely, otherwise I would have made the changes and done the PR myself. So, this should be better phrased into something like:

> Should the digital solution be implemented in the form of a website or an app? In the case of an app, do we have to host the app on the app store ourselves?

2020-08-05 08:28 UTC, Zhiyuan-Amos commented on docs/to_clarify.md
> +1. If there is a need in additional API which is not provided by the existing systems, will they be assistance for us to create the additional APis? Or is there a possiblity where we inherit the code
> will the~~y~~**re** be assistance

> additional AP~~i~~**I**s

> possib**i**lity

2020-08-05 08:28 UTC, Zhiyuan-Amos commented on docs/to_clarify.md
> +
Unnecessary new lines

2020-08-05 08:28 UTC, Zhiyuan-Amos commented on docs/to_clarify.md
> +    d.If inheriting their codebase, please provide us the architecture knowledge so that we can write the code in consistent manner.
Missing space after d.

2020-08-05 08:28 UTC, Zhiyuan-Amos commented on docs/to_clarify.md
> +    1. Any preferred frameworks?
Content placed in wrong segment

2020-08-05 08:28 UTC, Zhiyuan-Amos commented on docs/to_clarify.md
> +1. Can you run through with us the current digital concierge process? Please do share with us on the idea how you want it to be integrated. This will help us have a better understanding of the pain p
Missing new line after header

2020-08-05 08:28 UTC, Zhiyuan-Amos commented on docs/to_clarify.md
> +1. We have looked up some certain latest existing solutions on HotelTechReport. Here is some of the existing solutions that i have narrowed down.
> Here ~~is~~ are some

> that ~~i~~**I** have

2020-08-05 08:28 UTC, Zhiyuan-Amos commented on docs/to_clarify.md
> +    c. Are we supposed to inherit the current codebase and integrate or Build a new system from scratch?
> or ~~B~~**b**uild a

2020-08-05 11:32 UTC, alvinlim540 commented
> Made a brief review. In summary, there are multiple English mistakes in the document. Ideally, we don't want to spend time reviewing each other's English, so put your content through a English checker first before submitting a PR.
> 
> Also, there are multiple stylistic issues e.g. unnecessary new lines, missing new line. To ensure that the content is easy to read and modify, we should keep the style the same, as if this document is done by a single person.
> 
> The above also applies for how the content is being written. For example:
> 
> > f. Techstack related:
> > 1. Any preferred frameworks?
> 
> Our questions are written in complete sentences, so this question is out of place. It should have been better phrased as something like:
> 
> > Are there any restrictions on the tech stack used for implementing the solution?
> 
> Lastly, I tend to type in a more casually and less refined over text, which should not be directly copied here. For e.g.
> 
> > Front-end: Are we supposed to host the app on app store? Or do we need an app, or just web will do?
> 
> I type in such a manner so that I don't spend that much time to phrase everything nicely, otherwise I would have made the changes and done the PR myself. So, this should be better phrased into something like:
> 
> > Should the digital solution be implemented in the form of a website or an app? In the case of an app, do we have to host the app on the app store ourselves?

I will take note of the points and further improve on crafting a better sentence. Thank you for the effort in correcting me.

2020-08-07 11:46 UTC, merged